Update Git_ backup & restore

diff --git a/Git_ backup & restore b/Git_ backup & restore
--- a/Git_ backup & restore
+++ b/Git_ backup & restore
@@ -125,6 +125,28 @@ echo "===== DR Restore Completed Successfully =====" | tee -a "$LOGFILE"
 
 
 
+==========================================================================================================================================================================
+
+#!/bin/bash
+./opt/git.sh
+
+EXIT_STATUS=echo $?
+
+if [ $EXIT_STATUS -ne 0 ]; then
+    echo "/opt/git.sh failed. Running alternative commands for database reset and restore."  >>/tmp/git/git.log
+    gitlab-psql  <<EOF
+\c postgres
+select pg_terminate_backend(pid) from pg_stat_activity where datname='gitlabhq_production';
+select pg_terminate_backend(pid) from pg_stat_activity where datname='gitlabhq_production';
+drop database gitlabhq_production;
+create database gitlabhq_production;
+EOF
+
+gitlab-rake gitlab:backup:restore force=yes
+else
+    echo "/opt/git.sh executed successfully. No alternative actions taken."  >>/tmp/git/git.log
+fi
+
 
 
 
