Update Git_ backup & restore

diff --git a/Git_ backup & restore b/Git_ backup & restore
--- a/Git_ backup & restore
+++ b/Git_ backup & restore
@@ -169,5 +169,38 @@ else
     echo "/opt/git.sh executed successfully. No alternative actions taken." | tee -a /var/log/gitlab_dr_restore.log
 fi
 
+============================Final script=======================================================
+
+#!/bin/bash
+
+sh /opt/git.sh
+EXIT_STATUS=$?
+
+if [ "$EXIT_STATUS" -ne 0 ]; then
+    echo "/opt/git.sh failed. Running alternative commands for database reset and restore." | tee -a /var/log/gitlab_dr_restore.log
+
+    gitlab-psql <<EOF
+\c postgres
+select pg_terminate_backend(pid) from pg_stat_activity where datname='gitlabhq_production';
+select pg_terminate_backend(pid) from pg_stat_activity where datname='gitlabhq_production';
+drop database gitlabhq_production;
+create database gitlabhq_production;
+EOF
+
+    if [ $? -eq 0 ]; then
+        sudo gitlab-rake gitlab:backup:restore force=yes
+    else
+        echo "Database reset failed. Skipping restore." | tee -a /var/log/gitlab_dr_restore.log
+        exit 1
+    fi
+else
+    echo "/opt/git.sh executed successfully. No alternative actions taken." | tee -a /var/log/gitlab_dr_restore.log
+fi
+
+
+
+==================================================
+0 2 * * * /bin/bash /root/script.sh >> /var/log/gitlab_cron.log 2>&1
+
 
 
